name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main', 'master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (ffmpeg for pydub)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt || true
          pip install pytest pytest-cov requests

      - name: Run tests
        env:
          PINECONE_API_KEY: ""
          SUPABASE_URL: ""
          SUPABASE_ANON_KEY: ""
          SARVAM_API_KEY: ""
          GOOGLE_API_KEY: ""
          EMBEDDING_PROVIDER: "local"
          TEST_DB: "0"
        run: |
          pytest -q


